/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinador3.pkg0;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.*;
import static jdk.nashorn.internal.objects.NativeMath.log;

/**
 *
 * @author Abrahan
 */
public class Vjuego extends javax.swing.JFrame {
public int Files=0;
public JLabel imagenes[][];
public int cartas=0,lanzamientos=0;

    /**
     * Creates new form Vjuego
     */
    public Vjuego() {
        initComponents();
       // llenarMat();
       //MatrixImagen();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        col1 = new javax.swing.JButton();
        col2 = new javax.swing.JButton();
        col3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));

        jButton1.setText("Menu Principal");
        jButton1.setActionCommand("btnVolverM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        col1.setText("Columna1");
        col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ActionPerformed(evt);
            }
        });

        col2.setText("columna2");
        col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col2ActionPerformed(evt);
            }
        });

        col3.setText("columna3");
        col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(col1)
                .addGap(233, 233, 233)
                .addComponent(col2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(col3)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(col3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(col1)
                        .addComponent(col2)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void MatrixImagen()
    {
      GridLayout prueb = new GridLayout(cartas,3,50,50);
       panel.setLayout(prueb);
   
        int posX=50,posY=100,altura=80,anchura=150, cont=1;
      
        for (int i = 0; i < cartas; i++)
        {
            for (int j = 0; j < 3; j++) 
            {
                JLabel prie= new JLabel();
            
            imagenes[i][j]= prie;
            
           // imagenes[i][j].setBounds(posX, posY, anchura, altura);
           //imagenes[i][j].setText("aquitoy "+(cont)+" Pos "+i+","+j);
        //   imagenes[i][j].setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
           
            //imagenes[i][j].setIcon(new ImageIcon(getClass().getResource("/adivinador3/dirImage/Letras_MsChris("+cont+").jpg")));

           ImageIcon img = new ImageIcon(getClass().getResource("/adivinador3/dirImage/Letras_MsChris("+cont+").jpg"));
           Icon icono= new ImageIcon(img.getImage().getScaledInstance(180,80 ,100));
           imagenes[i][j].setIcon(icono);
          
           panel.add(imagenes[i][j]);
            
            posX=(posX+310);
            cont++;
                
                
            }
            posY= (posY+100);
            posX=50;
           // cont++;
            
        }
      
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

this.dispose();
MenuPrincipal menPrinc = new MenuPrincipal();
menPrinc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ActionPerformed
//GridLayout prueb = new GridLayout(cartas,3,50,50);
  //      panel.setLayout(prueb);
   moverCol1();
       int posX=50,posY=100,altura=80,anchura=150, cont=1; 
        for (int i = 0; i < cartas; i++)
        {
            for (int j = 0; j < 3; j++) 
            {
              //JOptionPane.showMessageDialog(null,"movercol1");
             imagenes[i][j].setBounds(posX, posY, anchura, altura);
              panel.add(imagenes[i][j]);
            
           
               posX=(posX+310);
               cont++;
                  
                
            }
           
             posY= (posY+100);
            posX=50;
        }

     lanzamientos++;
     Adivinar(lanzamientos);
    }//GEN-LAST:event_col1ActionPerformed

    private void col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col3ActionPerformed
     
//GridLayout prueb = new GridLayout(cartas,3,50,50);
   //panel.setLayout(prueb);
   moverCol3();
        int posX=50,posY=100,altura=80,anchura=150, cont=1; 
        for (int i = 0; i < cartas; i++)
        {
            for (int j = 0; j < 3; j++) 
            {
              
                imagenes[i][j].setBounds(posX, posY, anchura, altura);  
            panel.add(imagenes[i][j]);
            
            posX=(posX+310);
               cont++;
        }
          posY= (posY+100);
            posX=50;
        }

        // TODO add your handling code here:
        lanzamientos++;
     Adivinar(lanzamientos); 
        
    }//GEN-LAST:event_col3ActionPerformed

    private void col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col2ActionPerformed

        //GridLayout prueb = new GridLayout(cartas,3,50,50);
        //panel.setLayout(prueb);
   moverCol2();
       int posX=50,posY=100,altura=80,anchura=150, cont=1;  
        for (int i = 0; i < cartas; i++)
        {
            for (int j = 0; j < 3; j++) 
            {
                imagenes[i][j].setBounds(posX, posY, anchura, altura);  
            panel.add(imagenes[i][j]);
        
                 posX=(posX+310);
               cont++;
                
            }
              posY= (posY+100);
            posX=50;
           
        }        // TODO add your handling code here:
        
         lanzamientos++;
     Adivinar(lanzamientos);
    }//GEN-LAST:event_col2ActionPerformed

    void moverCol3()
{
    
JLabel aux [][] = new JLabel[cartas][3];
int acum=1, cont=0;

    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
                if(acum<=cartas)
                {aux [i][j]= imagenes[cont][0];
               // JOptionPane.showMessageDialog(null, ""+acum);
                cont++;
                }
                
                if (acum==(cartas+1))
                {   cont=0;
                    
                aux[i][j]=imagenes[cont][2];
              //   JOptionPane.showMessageDialog(null, ""+acum);
                
                cont++;
                }
                
                if ( acum>(cartas+1) && acum<=(2*cartas))
                {
                    
                aux[i][j]=imagenes[cont][2];
                cont++;
            //     JOptionPane.showMessageDialog(null, ""+acum);
                
                }
                
                if (acum==((2*cartas)+1))
                {
                   cont=0;
                    
                aux[i][j]=imagenes[cont][1];
               // JOptionPane.showMessageDialog(null, ""+acum);
                cont++;
                }
                
                if ( acum>((2*cartas)+1) && acum<=(3*cartas))
                {
                    
                aux[i][j]=imagenes[cont][1];
                cont++;
               // JOptionPane.showMessageDialog(null, ""+acum);
                
                }
                
                
                
                
            acum++;
            
        }
        
    }
    
    
    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
            imagenes[i][j]= aux[i][j];
            
        }
        
    }
    
    

    
}

void moverCol2()
{JLabel aux [][] = new JLabel[cartas][3];
int acum=1, cont=0;

    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
                if(acum<=cartas)
                {aux [i][j]= imagenes[cont][0];
                
                cont++;
                }
                
                if (acum==(((cartas)+1)))
                {   cont=0;
                    
                aux[i][j]=imagenes[cont][1];
                
                cont++;
                }
                
                if ( acum>((cartas)+1) && acum<=(2*cartas))
                {
                    
                aux[i][j]=imagenes[cont][1];
                cont++;
                
                }
                
                if (acum==((2*cartas)+1))
                {
                   cont=0;
                    
                aux[i][j]=imagenes[cont][2];
                
                cont++;
                }
                
                if ( acum>((2*cartas)+1) && acum<=(3*cartas))
                {
                    
                aux[i][j]=imagenes[cont][2];
                cont++;
                
                }
                
                
                
                
            acum++;
            
        }
        
    }
    
    
    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
            imagenes[i][j]= aux[i][j];
            
        }
        
    }
    
    
}


void moverCol1()
{JLabel aux [][] = new JLabel[cartas][3];

int acum=1, cont=0;

    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
                if(acum<=cartas)
                {aux [i][j]= imagenes[cont][1];
                
                cont++;
                }
                
                if (acum==(cartas+1))
                {   cont=0;
                    
                aux[i][j]=imagenes[cont][0];
                
                cont++;
                }
                
                if ( acum>(cartas+1) && acum<=(2*cartas))
                {
                    
                aux[i][j]=imagenes[cont][0];
                cont++;
                
                }
                
                if (acum==((2*cartas)+1))
                {
                   cont=0;
                    
                aux[i][j]=imagenes[cont][2];
                
                cont++;
                }
                
                if ( acum>((2*cartas)+1) && acum<=(3*cartas))
                {
                    
                aux[i][j]=imagenes[cont][2];
                cont++;
                
                }
                
                
                
                
            acum++;
            
        }
        
    }
    
    for (int i = 0; i < cartas; i++) {
        for (int j = 0; j < 3; j++) {
            
            imagenes[i][j]= aux[i][j];
            
        }
        
    }
    
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vjuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vjuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton col1;
    private javax.swing.JButton col2;
    private javax.swing.JButton col3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
   // private  JLabel imagenes[][]= new JLabel [getFilas()][3];
    
    public void crearMatrizImagenes(int b)
    {
    imagenes= new JLabel [b][3];
    cartas=b;
    }
    public void Adivinar(int lanzamiento)
    {int  bandera=0;
        double val=Math.ceil(loga((cartas*3),3));
        int nlanzamiento= (int)val ;
       // JOptionPane.showMessageDialog(null, "lanzamientos "+nlanzamiento);
        
        if(nlanzamiento==lanzamiento)
        {
            int b= ((cartas*3)+1)/2;
            
            for (int i = 0; i < cartas; i++) {
                for (int j = 0; j < 3; j++) {
                    
                    if(b== (bandera))
                    {
                     JOptionPane.showMessageDialog(rootPane, "La carta que elegiste es:", "", JOptionPane.PLAIN_MESSAGE, imagenes[i][j-1].getIcon());
                    }
                    
                    bandera++;
                }
            }
        }
    
    }
    
   private static Double loga(double num, int base) {
      return (Math.log10(num) / Math.log10(base));
   }
    
    
}
